### ISSUE TITLE
Feature: Sign In and Sign Up functionality for the app #GSSoc'24

### ISSUE THREAD

**Issue by HemangMishra1234** [sourabhkumar47/ResQFood#1]
I want to add Sign In and Sign Up for the app using Firebase.

**Comment by shivanshu11092003** [comment]
Assign this to me and Tell me more about what kind sign In and sign up like Google Sign ,facebook sign , Mobile Number Otp Sign

**Comment by Qomfortzone** [comment]
Under GSSoc i would like to work on this issue. Please Assign this to me

**Comment by realHKV** [comment]
Under gssoc 24 i would like to contribute

**Comment by Harshi-63** [comment]
i would like to work on this issue under #GSSoC24

**Comment by Varun-Sethi-Dev** [comment]
I would like to work on the sign in and sign up functionality assign this to me #gssoc2024

**Comment by hdhimalay** [comment]
Sir, I would like to work on the sign in and sign up functionality , kindly assign this to me #GSSoc2024

**Comment by Tejasvi-Tikoo** [comment]
I want to make 'sign in' and 'register' with phone number, email and google using firebase.

**Comment by HemangMishra1234** [comment]
> @HemangMishra1234 we need login with phone no (Mainly) and give Google and email options too, should I assign this to you?

Yes Sir. I am ready

**Comment by sourabhkumar47** [comment]
> > @HemangMishra1234 we need login with phone no (Mainly) and give Google and email options too, should I assign this to you?
> 
> Yes Sir. I am ready

Okay, Great

**Comment by Anushaamar111** [comment]
i would like to work on this issue under #GSSoC24

**Comment by HemangMishra1234** [comment]
> > > @HemangMishra1234 we need login with phone no (Mainly) and give Google and email options too, should I assign this to you?
> > 
> > Yes Sir. I am ready
> 
> Okay, Great

@sourabhkumar47 Sir, I have already started working on the project.
Here are the details, 
Phone number sign in is available on the first screen. Along with that, alternative authentication methods of email and google sign in are added. After authentication, the name of the restraunt is also asked along with its address, and these details are stored in Firestore.

Please add gssoc and level labels to the issue. Also, let me know if any changes have to be added.

**Comment by sourabhkumar47** [comment]
> > > > @HemangMishra1234 we need login with phone no (Mainly) and give Google and email options too, should I assign this to you?
> > > 
> > > 
> > > Yes Sir. I am ready
> > 
> > 
> > Okay, Great
> 
> @sourabhkumar47 Sir, I have already started working on the project. Here are the details, Phone number sign in is available on the first screen. Along with that, alternative authentication methods of email and google sign in are added. After authentication, the name of the restraunt is also asked along with its address, and these details are stored in Firestore.
> 
> Please add gssoc and level labels to the issue. Also, let me know if any changes have to be added.

Yaa , it's good to start the work
