### ISSUE TITLE
💡[FEATURE]:  Implementing Side Navigation

### ISSUE THREAD

**Issue by Saumya-28** [sourabhkumar47/ResQFood#101]
Implementing Side Navigation for easy user flow and navigation in JetPack Compose. Kindly assign this issue to me, I am a GSSOC contributor.

**Comment by sourabhkumar47** [comment]
> Hi @sourabhkumar47 ! Kindly add the gssoc as well as the level tag for this issue.

When you raise a PR, it will be assigned based on the complexity of the code you have written.

**Comment by Saumya-28** [comment]
I have raised a PR please review and assign the tags .
