### ISSUE TITLE
📝[Docs]: Update README.md [Redesign README Image]

### ISSUE THREAD

**Issue by me-shweta** [sourabhkumar47/ResQFood#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am Shweta Meena. Under GSSOC'24, I'm interested in redesigning the README Image to enhance its visual appeal. Assign me this task!

<img width="492" alt="Capture" src="https://github.com/sourabhkumar47/ResQFood/assets/119609866/e1f8c318-be24-4a68-a4d1-105e1433c854">

### Suggested Change

The current design is also very good, but I think it can be made even more attractive by adding some vibrant colors and making a few minor changes.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sourabhkumar47** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Issue Description
> 
> I am Shweta Meena. Under GSSOC'24, I'm interested in redesigning the README Image to enhance its visual appeal. Assign me this task!
> 
> <img width="492" alt="Capture" src="https://github.com/sourabhkumar47/ResQFood/assets/119609866/e1f8c318-be24-4a68-a4d1-105e1433c854">
> 
> 
> ### Suggested Change
> 
> The current design is also very good, but I think it can be made even more attractive by adding some vibrant colors and making a few minor changes.
> 
> ### Rationale
> 
> _No response_
> 
> ### Urgency
> 
> Medium
> 
> ### Record
> 
> - [X] I have read the Contributing Guidelines
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Assigned

**Comment by me-shweta** [comment]
@sourabhkumar47 Also, add the necessary labels for GGSOC. :)

**Comment by me-shweta** [comment]
**@sourabhkumar47 I have created some designs. Here they are.**

![7](https://github.com/sourabhkumar47/ResQFood/assets/119609866/65ef63bd-332b-4ba0-b2f3-9b46e92435d5)
![3](https://github.com/sourabhkumar47/ResQFood/assets/119609866/e3bdc789-2384-44e1-80a4-c63ec49a4807)
![5](https://github.com/sourabhkumar47/ResQFood/assets/119609866/a0a95f24-4a87-4c3b-a636-4ca4fac335ef)
![6](https://github.com/sourabhkumar47/ResQFood/assets/119609866/b808775e-502e-4b74-a2f1-8167188e9032)
![2](https://github.com/sourabhkumar47/ResQFood/assets/119609866/0d0de0e6-eb8e-48fa-8ec1-39cbdf79bd18)
![1](https://github.com/sourabhkumar47/ResQFood/assets/119609866/a0b0abb8-4f46-4d8a-b1c4-5b50269b5b63)
![4](https://github.com/sourabhkumar47/ResQFood/assets/119609866/0aca1e83-e801-44f0-b33d-856270b16116)


**Let me know which design suits you best and if there are any changes you would like to make.**

**Comment by sourabhkumar47** [comment]
Last one looks good

**Comment by me-shweta** [comment]
@sourabhkumar47 cool! Add the required labels for GGSOC, such as the level and GGSOC label. Then, I'll proceed with the PR. 
okay ??

**Comment by me-shweta** [comment]
@sourabhkumar47 
As this is a counted contribution guidelines provided in the PNG
<img width="512" alt="Capture" src="https://github.com/sourabhkumar47/ResQFood/assets/119609866/04d58049-4c7a-4975-bb6c-2a4d531a7ac9">

**Comment by me-shweta** [comment]
Shall I proceed with the pr ??

**Comment by sourabhkumar47** [comment]
> Shall I proceed with the pr ??

yes

**Comment by me-shweta** [comment]
**@sourabhkumar4 Please don't forget to do assign this PR to me and add the same labels as the issue before merging the pull request. Only then will this contribution be counted in GGSOC.**
