### ISSUE TITLE
💡[Feature]: Add GitHub Actions workflow to run gradle build on push and pull request

### ISSUE THREAD

**Issue by OkelloSam21** [sourabhkumar47/ResQFood#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to automate our build process to ensure that our code is consistently built and tested. This will involve creating a GitHub Actions workflow that runs gradle build on every push and pull request.

Tasks:

- Create a new GitHub Actions workflow file (.github/workflows/gradle-build.yml).
- Configure the workflow to trigger on push and pull request events.
- Add a step to check out the code.
- Add a step to set up JDK.
- Add a step to run gradle build.
- Test the workflow to ensure it runs correctly on push and pull request events.

### Use Case

- Consistency: Automating the build process ensures that the codebase is consistently built and tested with every change, reducing the likelihood of build-related issues.
- Early Detection: By running gradle build on every push and pull request, potential issues are caught early in the development cycle, leading to faster fixes and higher code quality.
- Efficiency: Developers save time and effort by not having to manually run builds and tests, allowing them to focus on writing code and implementing features.
- Continuous Integration: Integrating this workflow supports a continuous integration practice, ensuring that the codebase is always in a deployable state.
- Transparency: The workflow provides visibility into the build status for all team members, making it easier to track the health of the project.

### Benefits

- Improved Code Quality: Automated builds and tests ensure immediate validation of code changes, leading to higher overall code quality.
- Reduced Manual Effort: Developers are relieved from manually running builds and tests, allowing them to focus on more valuable work.
- Faster Feedback Loop: Immediate feedback on code changes helps developers quickly identify and fix issues, accelerating the development process.
- Consistency and Reliability: A consistent and repeatable build process reduces the risk of environment-related issues and build discrepancies.
- Enhanced Collaboration: Clear and visible build status for each push and pull request enhances team collaboration and helps maintain a healthy codebase.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sourabhkumar47** [comment]
Assigned

**Comment by OkelloSam21** [comment]
I think you can close this as completed
