### ISSUE TITLE
📝[Docs]: Updating readme.md file

### ISSUE THREAD

**Issue by kanishk-2** [sourabhkumar47/ResQFood#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

No intructions are given for beginners for contributing to project.
<img width="836" alt="1" src="https://github.com/sourabhkumar47/ResQFood/assets/157130879/0f4f20d0-3c39-409f-b752-5d8b0257b947">

### Suggested Change

Will be adding step by step procedure with commands for contributions for beginners to the project.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sourabhkumar47** [comment]
Assigned
