### ISSUE TITLE
Navigation And Screens

### ISSUE THREAD

**Issue by Lucky-chelani** [sourabhkumar47/ResQFood#22]
I would like to contribute in main screen and bottom navigation under gssoc'24

**Comment by Lucky-chelani** [comment]
Can you please explain the requirements of main screen ????

**Comment by sourabhkumar47** [comment]
read readme.md and analyse what is required so you can plan accordingly. 

> Can you please explain the requirements of main screen ????

read readme.md file and analyse what is required, then plan accordingly

**Comment by Lucky-chelani** [comment]
According to that there should be two login pages 
One for charty organization snd one for resturants
In resturants main page we will what to donate and in charity main page we will show them from where to pick up and where to donate

**Comment by Lucky-chelani** [comment]
And the login signup screens looks a bit laging and not a smooth ui can i recreate it accordingly ?
