### ISSUE TITLE
Fix: Google Auth Not working

### ISSUE THREAD

**Issue by Lucky-chelani** [sourabhkumar47/ResQFood#26]
i can fix this as when we click on googke it with shoe emails to login

**Comment by sourabhkumar47** [comment]
> i can fix this as when we click on googke it with shoe emails to login

try

**Comment by Lucky-chelani** [comment]
Any levels can i get for it under GSSOc'24

**Comment by sourabhkumar47** [comment]
> Any levels can i get for it under GSSOc'24



> i can fix this as when we click on googke it with shoe emails to login

This feature is functional, but only working on device who created this screen. So fix this accordingly.

**Comment by Lucky-chelani** [comment]
sure sir

**Comment by Lucky-chelani** [comment]
Please Enable google signing services in firebase

**Comment by Akshaykomar890** [comment]
is it still open @sourabhkumar47 can i work on it ?

**Comment by sourabhkumar47** [comment]
> is it still open @sourabhkumar47 can i work on it ?

No, it has been closed.
