### ISSUE TITLE
Feature: Profile Screen

### ISSUE THREAD

**Issue by HemangMishra1234** [sourabhkumar47/ResQFood#43]
Add a profile screen for users, giving option to add profile pictures.
Giving them option to edit their details like address, contact details, organization details, etc.
Also adding logout functionality.

**Comment by Pranishkafle6175** [comment]
Assign Me!

**Comment by sourabhkumar47** [comment]
> @sourabhkumar47  Please Assign Me!
> 

Already assigned, try another issue

**Comment by Adya-04** [comment]
I can resolve this issue! Please assign me

**Comment by sourabhkumar47** [comment]
> I can resolve this issue! Please assign me

You can try any other open issues.....like search bar on home screen
