### ISSUE TITLE
There is a issue with app icon please check the attach video.

### ISSUE THREAD

**Issue by Rajkumarbhakta** [sourabhkumar47/ResQFood#51]
There is a issue with app icon .

https://github.com/sourabhkumar47/ResQFood/assets/85289204/51c5ae31-e27b-4927-a8ba-5077ab9495c4

**Comment by Rajkumarbhakta** [comment]
Please assign this to me .

**Comment by sourabhkumar47** [comment]
> Please assign this to me .

assigned

**Comment by suyash-modi** [comment]
Please assign this to me .
