### ISSUE TITLE
Feature: Food Listings

### ISSUE THREAD

**Issue by sourabhkumar47** [sourabhkumar47/ResQFood#54]
Food Listings: Carousel of highlighted leftovers with images, names, prices etc.

**Comment by HemangMishra1234** [comment]
I want to work on this.

**Comment by sourabhkumar47** [comment]
assigned

**Comment by sourabhkumar47** [comment]
> @sourabhkumar47 can i work on this issue?

first, ask @HemangMishra1234 if he is still working or not, if he does not respond in 1 day you can start working.

**Comment by HemangMishra1234** [comment]
I'll get it done by tomorrow.
