### ISSUE TITLE
Feature: Ordering & Pickup (For Individuals)

### ISSUE THREAD

**Issue by sourabhkumar47** [sourabhkumar47/ResQFood#58]
- Item Details Screen: Detailed view of a leftover item.
- Image: Large image of the item.
- Description: Detailed description.
- Pickup Time: Display pickup window.
- Price: Display price.
- Claim Button: Button to claim the item.
- Order Confirmation Screen: Confirmation details of the order with directions to the restaurant.
- Payment Integration: Integrated payment options for items with a fee.

**Comment by ArtiGaund** [comment]
Is there a page for each individual leftover item? or cards with displaying all the leftover items, then move to the details page of items?

**Comment by sourabhkumar47** [comment]
> Is there a page for each individual leftover item? I will do it.

Welcome Arti, assigned

**Comment by ArtiGaund** [comment]
Do signup page work?

**Comment by sourabhkumar47** [comment]
> There is currently single page in the app, and signIn and signup don't work.

It works, try using email & password method

**Comment by ArtiGaund** [comment]
Its working now, I was doing some mistake.

**Comment by regxl2** [comment]
In the figma file it is not specified which image is for leftover screen(for individuals)  or do we have to take reference from the figma file and design on your own ?

**Comment by sourabhkumar47** [comment]
> In the figma file it is not specified which image is for ordering & pickup screen(for individuals) or do we have to take reference from the figma file and design on your own ?

you can take reference from Figma and design your own

**Comment by ArtiGaund** [comment]
@sourabhkumar47 Is it assigned to someone else also?

**Comment by sourabhkumar47** [comment]
> @sourabhkumar47 Is it assigned to someone else also?  

No

**Comment by regxl2** [comment]
> > @sourabhkumar47 Is it assigned to someone else also?  
> 
> No

Can you not assign to multiple at the same time ? If yes, can you also assign it to me

**Comment by ArtiGaund** [comment]
@sourabhkumar47 for pick time, do I have to add watch for time or text field? And for payment gateway, is there a button that will lead to a map?

**Comment by sourabhkumar47** [comment]
> @sourabhkumar47 for pick time, do I have to add watch for time or text field? And for payment gateway, is there a button that will lead to a map?

- add watch
- for payment, just add a button that navigate to any temporary screen

**Comment by sourabhkumar47** [comment]
> > > @sourabhkumar47 Is it assigned to someone else also?
> > 
> > 
> > No
> 
> Can you not assign to multiple at the same time ? If yes, please also assign it to me

No, you can take any other open issue or open your own issue

**Comment by ArtiGaund** [comment]
> > @sourabhkumar47 for pick time, do I have to add watch for time or text field? And for payment gateway, is there a button that will lead to a map?
> 
> * add watch
> * for payment, just add a button that navigate to any temporary screen

ok

**Comment by ArtiGaund** [comment]
![Screenshot_20240526_024501](https://github.com/sourabhkumar47/ResQFood/assets/38074085/62b13a90-0a28-431e-be92-1a03f99cd109)
![Screenshot_20240526_024507](https://github.com/sourabhkumar47/ResQFood/assets/38074085/5db561d4-a94f-489c-969a-72547e131291)
What will be the background color and button color? Its not accepting any other image; it may be because of size. Its not completed; there are a few modifications left. I will submit it tomorrow.

**Comment by ArtiGaund** [comment]
![Screenshot_20240527_013347](https://github.com/sourabhkumar47/ResQFood/assets/38074085/4cedf799-8b70-45a9-9c06-3e58c14dae87)
![Screenshot_20240527_013352](https://github.com/sourabhkumar47/ResQFood/assets/38074085/9d77a44c-9c12-4d0c-89c9-0bd243887f0d)
![Screenshot_20240527_013342](https://github.com/sourabhkumar47/ResQFood/assets/38074085/7e64642d-a604-4422-b1c6-97f0175b249c)
It's completed. Only customization of timepicker is left.
