### ISSUE TITLE
Improve Readme.md file.

### ISSUE THREAD

**Issue by Rajkumarbhakta** [sourabhkumar47/ResQFood#6]

**Comment by Rajkumarbhakta** [comment]
Hello I am from GSSoC'24. I want to work on this issue please assign me.

**Comment by AdityaPrakash-03** [comment]
I would like to do the work, and improve it so that other contributors can understand better and contribute with there skills

**Comment by Varun-Sethi-Dev** [comment]
I would like to work on it

**Comment by sourabhkumar47** [comment]
> Hello I am from GSSoC'24. I want to work on this issue please assign me.

Welcome Rajkumar, assigned
