### ISSUE TITLE
App  is crashing

### ISSUE THREAD

**Issue by Lucky-chelani** [sourabhkumar47/ResQFood#69]
![Uploading Screenshot_20240518-161909_Device care.jpg…]()

**Comment by HemangMishra1234** [comment]
@Lucky-chelani Screenshot is not loading. Please reshare.

**Comment by Lucky-chelani** [comment]
![Screenshot_20240518-161909_Device care](https://github.com/sourabhkumar47/ResQFood/assets/134550399/6c3ec0be-b53c-48a2-a688-41e95ee6acfd)

**Comment by HemangMishra1234** [comment]
Is the app not opening or crashing at some point. Let me know so that I can check if there is any issue in my code.

**Comment by Lucky-chelani** [comment]
Not opening @HemangMishra1234

**Comment by HemangMishra1234** [comment]
It is opening for me. Once you check the logcat to see the reason of bug

**Comment by Lucky-chelani** [comment]
Sure did you sync the fork ??

**Comment by HemangMishra1234** [comment]
It is not. Wait, I'll see to it. Thanks
