### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [sourabhkumar47/ResQFood#7]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by sourabhkumar47** [comment]
> Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.
> 
> Please assign this issue to me.

Assigned

**Comment by suhanipaliwal** [comment]
I have started working on this issue. Could you please label this issue under GSSOC'24 and also label an appropriate level like Level 1, 2 or 3.
