### ISSUE TITLE
add Horzontal pager

### ISSUE THREAD

**Issue by regxl2** [sourabhkumar47/ResQFood#80]
![IssueHorizontalPager](https://github.com/sourabhkumar47/ResQFood/assets/33978646/a04f384a-d3ec-4ebc-a07e-8c84e53c7967)
for better user experience add HorizontalPager to  navigate from My Orders tab to More tab by swiping left and right .
Plus I can reduce the redundant code in this screen.

Can you assign me this feature request to me If you think it is necessary

**Comment by sourabhkumar47** [comment]
> 
> ![IssueHorizontalPager](https://github.com/sourabhkumar47/ResQFood/assets/33978646/a04f384a-d3ec-4ebc-a07e-8c84e53c7967)
> for better user experience add HorizontalPager to  navigate from My Orders tab to More tab by swiping left and right .
> Plus I can reduce the redundant code in this screen.
> 
> 
> Can you assign me this feature request to me If you think it is necessary 

Okay, assigned
