### ISSUE TITLE
🪲[Bug]: Problem in Main Activity and gradle

### ISSUE THREAD

**Issue by regxl2** [sourabhkumar47/ResQFood#92]
Currently there is issue in this repo, it is not building there is some error in gradle and  MainActivity

**Comment by regxl2** [comment]
Admin please respond if someone is working on the issue. I was fixing the issue when i was going to rasie a PR the issue has been resolved, you merged someone PR .

**Comment by sourabhkumar47** [comment]
> Admin please respond if someone is working on the issue. I was fixing the issue when i was going to rasie a PR the issue has been resolved, you merged someone PR .

you can work on it

**Comment by regxl2** [comment]
![Screenshot_20240530_001616](https://github.com/sourabhkumar47/ResQFood/assets/33978646/6cc4bd0d-29b9-4ff3-b97f-88ec565238cc)
1. Fixed the issue, it was navigating to OrderConfirmScreen without selecting any time.

![image](https://github.com/sourabhkumar47/ResQFood/assets/33978646/ddabaa2b-c7a9-425d-ba70-d3f37fe4d930)
2. Replaced with the new library catalog declaration.

![Screenshot from 2024-05-30 00-39-21](https://github.com/sourabhkumar47/ResQFood/assets/33978646/4d3bb772-50bc-4a26-945e-8a43b23054f4)
3. Fixed the view Item Details button, It was even appearing on the profile screen
4. In OrderConfirmScreen,  on clicking the place order button  it was navigating back to OrderConfrimScreen which was causing stacking of the same activity , I made it navigate back to MainScreen .


These above changes i have made...please review it ... i am raising PR.
